/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UIMappingSelector.java
 *
 * Created on 21-Nov-2011, 13:06:11
 */

package uk.ac.brookes.regcmantic.rcm.phase34.ui;

import uk.ac.brookes.regcmantic.helper.gui.RcmExtendedFrame;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JProgressBar;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import uk.ac.brookes.regcmantic.helper.util.Print;

/**
 *
 * @author Krish
 */
public class _4_UIMappingSelector extends RcmExtendedFrame {

    /** Creates new form UIMappingSelector */
    public _4_UIMappingSelector() {
        init();
        process();
        setVisible(true);
    }

    private void init(){
        Print.prln("MappingSelector initialised...");
        mappingTableModel = new _3_MappingTableModel();
        initComponents();
        addProgressBars();
        setCells();
    }
    private void process(){
        getLblTitle().setText("Mapping Selector");
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e){
                int row=table.rowAtPoint(e.getPoint());
                int col= table.columnAtPoint(e.getPoint());
                if (table.getColumnName(col).equalsIgnoreCase("Detail")){
                    showDetail(row);
                }
                if (table.getColumnName(col).equalsIgnoreCase("Mapped")){
                     if (getMappingTableModel().getMappingData().getMappingList().get(row).isAccepted()){
                         getMappingTableModel().getMappingData().getMappingList().get(row).setAccepted(false);
                     } else{
                    getMappingTableModel().getMappingData().getMappingList().get(row).setAccepted(true);
                     }
                }
        }});
    }

    private void addProgressBars(){
        TableColumn sColumn =table.getColumn("Subject Score");
        TableColumn aColumn =table.getColumn("Action Score");
        sColumn.setCellRenderer(new ProgRenderer());
        aColumn.setCellRenderer(new ProgRenderer());
        sColumn.setMaxWidth(20);
        aColumn.setMaxWidth(20);
    }

    private void setCells(){
        table.getColumn("Mapping ID").setMaxWidth(100);
        table.getColumn("Mapped").setMaxWidth(100);
        table.getColumn("Detail").setMaxWidth(200);

        TableColumn c  = table.getColumn("Mapping ID");
        c.setCellRenderer(new TextCellRenderer());
      
    }
    private void showDetail(int row){
        _5_UIMappingDetails mappingDetails = new _5_UIMappingDetails(this, row);
}

    public _3_MappingTableModel getMappingTableModel() {
        return mappingTableModel;
    }

    public void setMappingTableModel(_3_MappingTableModel mappingTableModel) {
        this.mappingTableModel = mappingTableModel;
    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        table.setBackground(new java.awt.Color(0, 255, 204));
        table.setFont(new java.awt.Font("Georgia", 0, 15)); // NOI18N
        table.setModel(mappingTableModel);
        table.setCellSelectionEnabled(true);
        table.setRowHeight(50);
        table.setRowMargin(10);
        table.setShowVerticalLines(false);
        jScrollPane1.setViewportView(table);

        btnSave.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel)
                        .addGap(276, 276, 276)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        mappingTableModel.getMappingData().writeFile();
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
    
    private _3_MappingTableModel mappingTableModel;
    private int selectedRow;
    private int selectedColumn;

}
    class ProgRenderer implements TableCellRenderer{
    @Override
    public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column){
        return (JProgressBar)value;
    }
}

    class TextCellRenderer implements TableCellRenderer{
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            JTextArea t = new JTextArea();
            t.setText(value.toString());
            t.setBackground(Color.GRAY);
            t.setForeground(Color.white);
            t.setFont(new java.awt.Font("Georgia", 1, 14));
            return t;
        }

    }

